### ISSUE TITLE
Sync airflow dags with S3

### ISSUE THREAD

**Issue by pesto93** [aws-containers/Airflow-on-Fargate#3]
I am fairly new to AWS and Airflow, I managed to deploy airflow using this repo and I was wondering how I sync my dags from s3 or github to the running containers?

**Comment by thechaithanya** [comment]
Check if this helps: https://tech.scribd.com/blog/2020/breaking-up-the-dag-repo.html

**Comment by cloneluke** [comment]
I just have a script to do a git clone on my dag repo in my container I can call as needed or at build time
